### PR TITLE
Refresh all mount caches after reducing

### LINKED ISSUE #10: Changes to own state of mounted stores should invalidate cache of ancestors
When a descendant of a mounted store updates its own state, we don't invalidate the cache of its ancestor mounted stores. This results in stale state appearing in the ancestor's own state.

# Repro
```
'use strict';

const redux = require('redux');
const reduxMountStore = require('./');
const assert = require('assert');
const immutable = require('object-path-immutable');

const store = redux.createStore(
	state => state,
	{},
	reduxMountStore
);

const hostStore = store.mount('host')(
	state => state,
	{}
);

const childStore = hostStore.mount('child')(
	(state, action) => {
		if (action.type === 'MUTATE_CHILD') {
			state = immutable.set(state, 'childOwn', 'new child');
		}

		return state;
	},
	{
		childOwn: 'child'
	}
);

childStore.dispatch({
	type: 'MUTATE_CHILD'
});

assert.deepEqual(store.getState(), {
	host: {
		child: {
			childOwn: 'new child'
		}
	}
});

assert.deepEqual(hostStore.getState(), {
	child: {
		childOwn: 'new child'
	}
});
```

This script can be run from the root of the repo to reproduce the bug. The second assertion will fail. Note that the first assertion is fine, because the changes are included in the new state we return from the root reducer.

### PR DESCRIPTION
**Pull request by lawnsea**
When a descendant mounted store of a mounted store updated its own state, that
is also a change to the ancestor mounted store's own state. However, as reported
in #10, we did not update the ancestor's cached own state to reflect that
change.

This patch adds a test reproducing the bug and fixes it by updating the cached
state of *all* mounts after reduction is complete. This does unnecessary work,
but assures correctness.

[Fix #10]

### CODE REVIEW

**Comment by lawnsea** [comment]
@lzilioli @slimelabs

**Comment by lzilioli** [comment]
Tested on my branch and it works

**Comment by lzilioli** [comment]
There seems to still be an issue with this.

If I have a component that is mounted as such:

```
store.mount('siteHeader', {
	/* eslint camelcase:0 */
	logo_link: (state)=>state.page.header.logo_link,
	ideas_link: (state)=>state.page.header.ideas_link,
	profile_link: (state)=>state.page.header.profile_link,
	join_link: (state)=>state.page.header.join_link,
	login_link: (state)=>state.page.header.login_link,
	popup_menu: (state)=>state.page.header.popup_menu,
	user_bar_menu: (state)=>state.page.header.user_bar_menu
})
```

And the component mounted here also has its own state that it stores in keys that are not described at mount time, then the own state is the only thing that end's up in the component;s mount point. None of the mapped properties show up.

**Comment by lzilioli** [comment]
Sorry to be pedantic, but I'm trying to make sense of the PR description to ensure I understand the changes correctly.

> This does unnecessary work, but assures correctness.

Is the unnecessary work to the end of assuring correctness? If so, wouldn't that work be considered necessary?

**Comment by lawnsea** [comment]
> And the component mounted here also has its own state that it stores in keys that are not described at mount time, then the own state is the only thing that end's up in the component;s mount point. None of the mapped properties show up.

I'm not quite following this, @lzilioli. Can you provide a minimal repro script?

**Comment by lawnsea** [comment]
> Is the unnecessary work to the end of assuring correctness? If so, wouldn't that work be considered necessary?

This patch refreshes the cache of all mounted stores, even those that were not modified or affected by modifications in descendants. This is correct (any mounted store that *was* modified or affected by modifications in descendants gets its cache updated), but may do unnecessary work.

For example, suppose there are mounted stores at `foo`, `foo.bar`, and `fiz`. The reducer for `foo.bar` modifies that mounted store's own state. This patch will refresh the cached own state of `foo`, which is necessary. It will also refresh that of `fiz`, which is not necessary.

**Comment by slimelabs** [comment]
> This patch adds a test reproducing the bug and fixes it by updating the cached
state of all mounts after reduction is complete. This does unnecessary work,
but assures correctness.

What's the performance look like if we just invalidate caches instead of updating them?

**Comment by lawnsea** [comment]
@slimelabs we can't do that with the current implementation: the cache is set eagerly and read from a property, instead of from a function, which would allow us to be lazy

**Comment by slimelabs** [comment]
@lzilioli I think you're saying one thing and I want to be sure that I'm correct.

Given:
- a root store with state `{a: 'a', b: 'b'}`
- a store mounted on the root store at `child` which views `a` and has its own data `c`

i.e.
```
const store = createStore(state => state, {a: 'a', b: 'b'}
const mountedStore = store.mount('child', {myA: state => state.a})({myC: 'c'})
```

I _think_ you're saying that you expect `store.getState()` to have this output:

```
{
  a: 'a',
  b: 'b',
  child: {
    myA: 'a',
    myC: 'c'
  }
}
```

If I'm correct and that's your expectation, we actually _don't_ expect that. The idea is that viewed state is visible _only_ to the mounted store because it's a calculation of store data. So we would see this output for `store.getState()`:

```
{
  a: 'a',
  b: 'b',
  child: {
    myC: 'c'
  }
}
```

And this output for `mountedStore.getState()`:

```
{
  myA: 'a',
  myC: 'c'
}
```

**Comment by slimelabs** [comment]
@lawnsea Okay, sounds like it's maybe a bigger scope conversation than this issue then. Are we just trying to get the bug fixed? If so, cool, but it might be worth thinking about whether this will negatively impact performance, since we've had issues with that.

**Comment by slimelabs** [comment]
👍 bueno 
🎱

**Pull request merged**
